name: diccon_evo
description: A new Diccon that work on many platforms.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.6+46

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # This lib to set windows size on Windows.
  window_manager: ^0.3.6
  # Provide ability to speak a provided word.
  flutter_tts: ^3.8.3
  http: ^1.1.0
  # A Flutter plugin for finding commonly used locations on the filesystem
  path_provider: ^2.1.1
  audioplayers: ^5.1.0
  # Package for Packaging Windows App
  msix: ^3.16.4
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  # Save settings
  shared_preferences: ^2.2.1
  # This package help us create a notification in the bottom app
  fluttertoast: ^8.2.2
  # State management combination
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Help us loaf svg image
  flutter_svg: ^2.0.7
  # Open link
  url_launcher: ^6.1.14
  # using firebase_core: ^2.10.0 get windows build without error
  firebase_core: ^2.17.0
  google_sign_in: ^6.1.5
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  firebase_app_check: ^0.2.0+1

  # custom icon
  font_awesome_flutter: ^10.5.0

  # localization
  i18n_extension: ^9.0.2
  flutter_localization: ^0.1.14
  # gpt
  chat_gpt_flutter: ^1.0.15
  # use to check internet connectivity
  internet_connection_checker: ^1.0.0+1
  # create dotted indicator for pageview
  smooth_page_indicator: ^1.1.0
  # create route for application
  go_router: ^11.1.2
  collection: ^1.17.0
  flutter_localizations:
    sdk: flutter
  # use for customizing theme
  dynamic_color: ^1.6.7
  flutter_material_color_picker: ^1.2.0
  #wave animation
  wave: ^0.2.2
  speech_to_text: ^6.3.0
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/dictionary/
    - assets/thesaurus/english_synonyms.json
    - assets/thesaurus/english_antonyms.json
    - assets/badges/
    - assets/essential/
    - assets/stories/
    - assets/stickers/
    - assets/theme/
    - assets/conversation_support/
    - assets/stickers/listening.png
msix_config:
  display_name: Diccon Evo
  publisher_display_name: Zeroboy
  identity_name: 24555Zeroboy.DicconEvo
  publisher: CN=DA7D2C99-987C-4B69-8953-17157F6E0E1A
  msix_version: 1.4.1.0
  logo_path: C:\Users\Zr\StudioProjects\diccon_evo\assets\dictionary\icon.ico
  store: true
